name: tecvid_analyzer
description: Tecvid Analiz Uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: ^6.0.0
  path_provider: ^2.1.2
  http: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
